- name: Deploy to Azure Storage
        uses: bacongobbler/azure-blob-storage-upload@v3.0.0
        with:
          source_dir: 'Front end repo'
          container_name: '$web'
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
